wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1694446747.422019
    t:
      1:
      - 1
      - 48
      - 55
      2:
      - 1
      - 48
      - 55
      3:
      - 2
      - 23
      4: 3.11.4
      5: 0.15.10
      8:
      - 1
      - 3
      - 5
